ClothesStore/ClothesStore/Areas/Admin/Controllers/SizesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClothesStore.Models;

namespace ClothesStore.Areas.Admin.Controllers
{
    public class SizesController : Controller
    {
        private TESTEntities db = new TESTEntities();

        // GET: Admin/Sizes
        public ActionResult Index()
        {
            return View(db.Sizes.ToList());
        }

        // GET: Admin/Sizes/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Size size = db.Sizes.Find(id);
            if (size == null)
            {
                return HttpNotFound();
            }
            return View(size);
        }


        // GET: Admin/Sizes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Sizes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SizeID,SizeName,IsHidden")] Size size)
        {
            if (ModelState.IsValid)
            {
                if (size.SizeID == null)
                {
                    size.SizeID = "S000";
                }
                db.Sizes.Add(size);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(size);
        }

        // GET: Admin/Sizes/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Size size = db.Sizes.Find(id);
            if (size == null)
            {
                return HttpNotFound();
            }
            return View(size);
        }

        // POST: Admin/Sizes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SizeID,SizeName,IsHidden")] Size size)
        {
            if (ModelState.IsValid)
            {
                db.Entry(size).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(size);
        }

        // GET: Admin/Sizes/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Size size = db.Sizes.Find(id);
            if (size == null)
            {
                return HttpNotFound();
            }
            return View(size);
        }

        // POST: Admin/Sizes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Size size = db.Sizes.Find(id);
            db.Sizes.Remove(size);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ClothesStore/ClothesStore/Areas/Admin/Views/Sizes/Create.cshtml
@model ClothesStore.Models.Size

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.Label = "Kích cỡ";
    ViewBag.FucLabel = "Thêm kích cỡ";
}

<section class="content">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="card">
            <div class="card-header border-bottom p-0 p-3 mx-1">
                <div class="col-sm-6 p-md-0">
                    <div class="welcome-text">
                        <h3 class="card-title">
                            <strong>@ViewBag.FucLabel</strong>
                        </h3>
                    </div>
                </div>
                <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                    <a href="@Url.Action("Index", "Sizes")" class="btn btn-primary">
                        Quay lại
                    </a>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-9">
                        <div class="form-group">
                            <label class="text-uppercase h6">
                                Tên màu sắc
                                <span class="text-danger">(*)</span>
                            </label>
                            @Html.EditorFor(model => model.SizeName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.SizeName, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-3"></div>
                </div>
            </div>
            <div class="card-footer">
                <div class="form-group m-0">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-success" />
                    </div>
                </div>
            </div>
        </div>
    }
</section>

ClothesStore/ClothesStore/Areas/Admin/Views/Sizes/Delete.cshtml
@model ClothesStore.Models.Size

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.Label = "Kích cỡ";
    ViewBag.FucLabel = "Xóa kích cỡ";
}

<section class="content">
    <div class="card">
        <div class="card-header border-bottom p-0 p-3 mx-1">
            <div class="col-sm-6 p-md-0">
                <div class="welcome-text">
                    <h3 class="card-title">
                        <strong>@ViewBag.FucLabel</strong>
                    </h3>
                </div>
            </div>
            <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                <a href="@Url.Action("Index", "Sizes")" class="btn btn-primary">
                    Quay lại
                </a>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table display p-0 m-0" style="min-width: 845px;">
                    <thead>
                        <tr>
                            <th>.#</th>
                            <th>Mã màu sắc</th>
                            <th>Tên màu sắc</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td></td>
                            <td>@Html.DisplayFor(model => model.SizeID)</td>
                            <td>@Html.DisplayFor(model => model.SizeName)</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card-footer">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-danger" />
                </div>
            }
        </div>
    </div>
</section>

ClothesStore/ClothesStore/Areas/Admin/Views/Sizes/Details.cshtml
@model ClothesStore.Models.Size

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.Label = "Kích cỡ";
    ViewBag.FucLabel = "Chi tiết kích cỡ";
}

<section class="content">
    <div class="card">
        <div class="card-header border-bottom p-0 p-3 mx-1">
            <div class="col-sm-6 p-md-0">
                <div class="welcome-text">
                    <h3 class="card-title">
                        <strong>@ViewBag.FucLabel</strong>
                    </h3>
                </div>
            </div>
            <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                <a href="@Url.Action("Edit", "Sizes", new { id = Model.SizeID })" class="btn btn-danger mr-2">
                    Sửa
                </a>
                <a href="@Url.Action("Index", "Sizes")" class="btn btn-primary">
                    Quay lại
                </a>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table display p-0 m-0" style="min-width: 845px;">
                    <thead>
                        <tr>
                            <th>.#</th>
                            <th>Mã màu sắc</th>
                            <th>Tên màu sắc</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td></td>
                            <td>@Html.DisplayFor(model => model.SizeID)</td>
                            <td>@Html.DisplayFor(model => model.SizeName)</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card-footer">
        </div>
    </div>
</section>

ClothesStore/ClothesStore/Areas/Admin/Views/Sizes/Edit.cshtml
@model ClothesStore.Models.Size

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.Label = "Kích cỡ";
    ViewBag.FucLabel = "Sửa kích cỡ";
}

<section class="content">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SizeID)
        <div class="card">
            <div class="card-header border-bottom p-0 p-3 mx-1">
                <div class="col-sm-6 p-md-0">
                    <div class="welcome-text">
                        <h3 class="card-title">
                            <strong>@ViewBag.FucLabel</strong>
                        </h3>
                    </div>
                </div>
                <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                    <a href="@Url.Action("Index", "Sizes")" class="btn btn-primary">
                        Quay lại
                    </a>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-9">
                        <div class="form-group">
                            <label class="text-uppercase h6">
                                Tên màu sắc
                                <span class="text-danger">(*)</span>
                            </label>
                            @Html.EditorFor(model => model.SizeName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.SizeName, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-3"></div>
                </div>
            </div>
            <div class="card-footer">
                <div class="form-group m-0">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-success" />
                    </div>
                </div>
            </div>
        </div>
    }
</section>

ClothesStore/ClothesStore/Areas/Admin/Views/Sizes/Index.cshtml
@model IEnumerable<ClothesStore.Models.Size>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.Label = "Kích cỡ";
    ViewBag.FucLabel = "Thông tin kích cỡ";
}

@section header{
    <!-- Datatable -->
    <link href="~/Public/vendor/datatables/css/jquery.dataTables.min.css" rel="stylesheet">
}
@section footer{
    <!-- Datatable -->
    <script src="~/Public/vendor/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/Public/js/plugins-init/datatables.init.js"></script>
}

<section class="content">
    <div class="card">
        <div class="card-header border-bottom p-0 p-3 mx-1">
            <div class="col-sm-6 p-md-0">
                <div class="welcome-text">
                    <h3 class="card-title">
                        <strong>Thông tin màu sắc</strong>
                    </h3>
                </div>
            </div>
            <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                <a href="@Url.Action("Create", "Sizes")" class="btn btn-success">
                    Thêm mới
                </a>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table id="example" class="display p-0" style="min-width: 845px;">
                    <thead>
                        <tr>
                            <th style="width: 10px">.#</th>
                            <th>Tên màu sắc</th>
                            <th>Chức năng</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td></td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.SizeName)
                                </td>
                                <td>
                                    <a href="@Url.Action("Edit", "Sizes", new { id = item.SizeID })" class="btn btn-success">Sửa</a>
                                    <a href="@Url.Action("Details", "Sizes", new { id = item.SizeID })" class="btn btn-primary">Xem</a>
                                    <a href="@Url.Action("Delete", "Sizes", new { id = item.SizeID })" class="btn btn-danger">Xóa</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card-footer">

        </div>
    </div>
</section>