ClothesStore/ClothesStore/Models/ClothingStyle.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothesStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClothingStyle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClothingStyle()
        {
            this.Clothes = new HashSet<Cloth>();
        }
    
        public string ClothingStyleID { get; set; }
        public string ClothingStyleName { get; set; }
        public string ClothingTypeID { get; set; }
        public bool IsHidden { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cloth> Clothes { get; set; }
        public virtual ClothingType ClothingType { get; set; }
    }
}

ClothesStore/ClothesStore/Areas/Admin/Controllers/ClothingStylesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClothesStore.Models;

namespace ClothesStore.Areas.Admin.Controllers
{
    public class ClothingStylesController : Controller
    {
        private TESTEntities db = new TESTEntities();

        // GET: Admin/ClothingStyles
        public ActionResult Index()
        {
            var clothingStyles = db.ClothingStyles.Include(c => c.ClothingType);
            return View(clothingStyles.ToList());
        }

        // GET: Admin/ClothingStyles/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClothingStyle clothingStyle = db.ClothingStyles.Find(id);
            if (clothingStyle == null)
            {
                return HttpNotFound();
            }
            return View(clothingStyle);
        }

        // GET: Admin/ClothingStyles/Create
        public ActionResult Create()
        {
            ViewBag.ClothingTypeID = new SelectList(db.ClothingTypes, "ClothingTypeID", "ClothingTypeName");
            return View();
        }

        // POST: Admin/ClothingStyles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ClothingStyleID,ClothingStyleName,ClothingTypeID,IsHidden")] ClothingStyle clothingStyle)
        {
            if (ModelState.IsValid)
            {
                if (clothingStyle.ClothingStyleID == null)
                {
                    clothingStyle.ClothingStyleID = "CS000";
                }
                db.ClothingStyles.Add(clothingStyle);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ClothingTypeID = new SelectList(db.ClothingTypes, "ClothingTypeID", "ClothingTypeName", clothingStyle.ClothingTypeID);
            return View(clothingStyle);
        }

        // GET: Admin/ClothingStyles/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClothingStyle clothingStyle = db.ClothingStyles.Find(id);
            if (clothingStyle == null)
            {
                return HttpNotFound();
            }
            ViewBag.ClothingTypeID = new SelectList(db.ClothingTypes, "ClothingTypeID", "ClothingTypeName", clothingStyle.ClothingTypeID);
            return View(clothingStyle);
        }

        // POST: Admin/ClothingStyles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ClothingStyleID,ClothingStyleName,ClothingTypeID,IsHidden")] ClothingStyle clothingStyle)
        {
            if (ModelState.IsValid)
            {
                db.Entry(clothingStyle).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ClothingTypeID = new SelectList(db.ClothingTypes, "ClothingTypeID", "ClothingTypeName", clothingStyle.ClothingTypeID);
            return View(clothingStyle);
        }

        // GET: Admin/ClothingStyles/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClothingStyle clothingStyle = db.ClothingStyles.Find(id);
            if (clothingStyle == null)
            {
                return HttpNotFound();
            }
            return View(clothingStyle);
        }

        // POST: Admin/ClothingStyles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            ClothingStyle clothingStyle = db.ClothingStyles.Find(id);
            if (clothingStyle != null)
            {
                clothingStyle.IsHidden = true; // Đánh dấu ẩn
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

ClothesStore/ClothesStore/Areas/Admin/Views/ClothingStyles/Create.cshtml
@model ClothesStore.Models.ClothingStyle

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.Label = "Kiểu quần áo";
    ViewBag.FucLabel = "Thêm kiểu quần áo";
}

<section class="content">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="card">
            <div class="card-header border-bottom p-0 p-3 mx-1">
                <div class="col-sm-6 p-md-0">
                    <div class="welcome-text">
                        <h3 class="card-title">
                            <strong>@ViewBag.FucLabel</strong>
                        </h3>
                    </div>
                </div>
                <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                    <a href="@Url.Action("Index", "ClothingTypes")" class="btn btn-primary">
                        Quay lại
                    </a>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-9">
                        <div class="form-group">
                            <label class="text-uppercase h6">
                                Tên kiểu quần áo
                                <span class="text-danger">(*)</span>
                            </label>
                            @Html.EditorFor(model => model.ClothingStyleName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ClothingStyleName, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <label class="text-uppercase h6">
                                Tên loại quần áo
                                <span class="text-danger">(*)</span>
                            </label>
                            @Html.DropDownList("ClothingTypeID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.ClothingTypeID, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-3"></div>
                </div>
            </div>
            <div class="card-footer">
                <div class="form-group m-0">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-success" />
                    </div>
                </div>
            </div>
        </div>
    }
</section>

ClothesStore/ClothesStore/Areas/Admin/Views/ClothingStyles/Delete.cshtml
@model ClothesStore.Models.ClothingStyle

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.Label = "Kiểu quần áo";
    ViewBag.FucLabel = "Xóa kiểu quần áo";
}


<section class="content">
    <div class="card">
        <div class="card-header border-bottom p-0 p-3 mx-1">
            <div class="col-sm-6 p-md-0">
                <div class="welcome-text">
                    <h3 class="card-title">
                        <strong>@ViewBag.FucLabel</strong>
                    </h3>
                </div>
            </div>
            <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                <a href="@Url.Action("Index", "ClothingStyles")" class="btn btn-primary">
                    Quay lại
                </a>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table display p-0 m-0" style="min-width: 845px;">
                    <thead>
                        <tr>
                            <th>.#</th>
                            <th>Mã kiểu quần áo</th>
                            <th>Tên kiểu quần áo</th>
                            <th>Tên loại quần áo</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td></td>
                            <td>@Html.DisplayFor(model => model.ClothingStyleID)</td>
                            <td>@Html.DisplayFor(model => model.ClothingStyleName)</td>
                            <td>@Html.DisplayFor(model => model.ClothingType.ClothingTypeName)</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card-footer">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-danger" />
                </div>
            }
        </div>
    </div>
</section>

ClothesStore/ClothesStore/Areas/Admin/Views/ClothingStyles/Details.cshtml
@model ClothesStore.Models.ClothingStyle

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.Label = "Kiểu quần áo";
    ViewBag.FucLabel = "Chi tiết kiểu quần áo";
}


<section class="content">
    <div class="card">
        <div class="card-header border-bottom p-0 p-3 mx-1">
            <div class="col-sm-6 p-md-0">
                <div class="welcome-text">
                    <h3 class="card-title">
                        <strong>@ViewBag.FucLabel</strong>
                    </h3>
                </div>
            </div>
            <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                <a href="@Url.Action("Edit", "ClothingStyles", new { id = Model.ClothingStyleID })" class="btn btn-danger mr-2">
                    Sửa
                </a>
                <a href="@Url.Action("Index", "ClothingStyles")" class="btn btn-primary">
                    Quay lại
                </a>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table display p-0 m-0" style="min-width: 845px;">
                    <thead>
                        <tr>
                            <th>.#</th>
                            <th>Mã kiểu quần áo</th>
                            <th>Tên kiểu quần áo</th>
                            <th>Tên loại quần áo</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td></td>
                            <td>@Html.DisplayFor(model => model.ClothingStyleID)</td>
                            <td>@Html.DisplayFor(model => model.ClothingStyleName)</td>
                            <td>@Html.DisplayFor(model => model.ClothingType.ClothingTypeName)</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card-footer">
        </div>
    </div>
</section>

ClothesStore/ClothesStore/Areas/Admin/Views/ClothingStyles/Edit.cshtml
@model ClothesStore.Models.ClothingStyle

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.Label = "Kiểu quần áo";
    ViewBag.FucLabel = "Sửa kiểu quần áo";
}

<section class="content">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ClothingStyleID)
        <div class="card">
            <div class="card-header border-bottom p-0 p-3 mx-1">
                <div class="col-sm-6 p-md-0">
                    <div class="welcome-text">
                        <h3 class="card-title">
                            <strong>@ViewBag.FucLabel</strong>
                        </h3>
                    </div>
                </div>
                <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                    <a href="@Url.Action("Index", "ClothingStyles")" class="btn btn-primary">
                        Quay lại
                    </a>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-9">
                        <div class="form-group">
                            <label class="text-uppercase h6">
                                Tên kiểu quần áo
                                <span class="text-danger">(*)</span>
                            </label>
                            @Html.EditorFor(model => model.ClothingStyleName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ClothingStyleName, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group">
                            <label class="text-uppercase h6">
                                Tên loại quần áo
                                <span class="text-danger">(*)</span>
                            </label>
                            @Html.DropDownList("ClothingTypeID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.ClothingTypeID, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-3"></div>
                </div>
            </div>
            <div class="card-footer">
                <div class="form-group m-0">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-success" />
                    </div>
                </div>
            </div>
        </div>
    }
</section>

ClothesStore/ClothesStore/Areas/Admin/Views/ClothingStyles/Index.cshtml
@model IEnumerable<ClothesStore.Models.ClothingStyle>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.Label = "Kiểu quần áo";
    ViewBag.FucLabel = "Thông tin kiểu quần áo";
}

@section header{
    <!-- Datatable -->
    <link href="~/Public/vendor/datatables/css/jquery.dataTables.min.css" rel="stylesheet">
}
@section footer{
    <!-- Datatable -->
    <script src="~/Public/vendor/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/Public/js/plugins-init/datatables.init.js"></script>
}

<section class="content">
    <div class="card">
        <div class="card-header border-bottom p-0 p-3 mx-1">
            <div class="col-sm-6 p-md-0">
                <div class="welcome-text">
                    <h3 class="card-title">
                        <strong>@ViewBag.FucLabel</strong>
                    </h3>
                </div>
            </div>
            <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                <a href="@Url.Action("Create", "ClothingStyles")" class="btn btn-success">
                    Thêm mới
                </a>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table id="example" class="display p-0" style="min-width: 845px;">
                    <thead>
                        <tr>
                            <th style="width: 10px">.#</th>
                            <th>Tên kiểu quần áo</th>
                            <th>Tên loại quần áo</th>
                            <th>Chức năng</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td></td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ClothingStyleName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ClothingType.ClothingTypeName)
                                </td>
                                <td>
                                    @if (item.IsHidden == false)
                                    {
                                        <a href="#" class="btn btn-success disabled"><i class="fa fa-toggle-on" aria-hidden="true"></i></a>
                                        <a href="@Url.Action("Edit", "ClothingStyles", new { id = item.ClothingStyleID })" class="btn btn-success">Sửa</a>
                                        <a href="@Url.Action("Delete", "ClothingStyles", new { id = item.ClothingStyleID })" class="btn btn-danger">Xóa</a>
                                        <a href="@Url.Action("Details", "ClothingStyles", new { id = item.ClothingStyleID })" class="btn btn-primary">Xem</a>
                                    }
                                    else
                                    {
                                        <a href="#" class="btn btn-danger disabled"><i class="fa fa-toggle-off" aria-hidden="true"></i></a>
                                        <a href="@Url.Action("Edit", "ClothingStyles", new { id = item.ClothingStyleID })" class="btn btn-success disabled">Sửa</a>
                                        <a href="@Url.Action("Delete", "ClothingStyles", new { id = item.ClothingStyleID })" class="btn btn-danger disabled">Xóa</a>
                                        <a href="@Url.Action("Details", "ClothingStyles", new { id = item.ClothingStyleID })" class="btn btn-primary">Xem</a>
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card-footer">

        </div>
    </div>
</section>